[package]
name = "opencvrs"
version = "0.1.0"
authors = ["dzwei <deweiworkmail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "*", features = ["buildtime-bindgen"] }